name: Deploy API to VPS

on:
  push:
    branches:
      - main   # or master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.APP_HOST }}
          username: ${{ secrets.APP_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/myhousingcircle/domains/api.myhousingcircle.com/public_html/myhousingcircle
            git pull origin main
            npm install --production
            pm2 restart myhousing-api
